#ifndef ICCINFO_H
#define ICCINFO_H

//Begin ICC Constants
#define DG_WHO_AM_I			0
#define DG_PLAYER_ARRIVED		1
#define DG_PLAYER_LEFT			2
#define DG_BULLET			3
#define DG_BLITZ			4
#define DG_STANDARD			5
#define DG_WILD				6
#define DG_BUGHOUSE			7
#define DG_TIMESTAMP			8
#define DG_TITLES			9
#define DG_OPEN				10
#define DG_STATE			11
#define DG_GAME_STARTED			12
#define DG_GAME_RESULT			13
#define DG_EXAMINED_GAME_IS_GONE	14
#define DG_MY_GAME_STARTED		15
#define DG_MY_GAME_RESULT		16
#define DG_MY_GAME_ENDED		17
#define DG_STARTED_OBSERVING		18
#define DG_STOP_OBSERVING		19
#define DG_PLAYERS_IN_MY_GAME		20
#define DG_OFFERS_IN_MY_GAME		21
#define DG_TAKEBACK			22
#define DG_BACKWARD			23
#define DG_SEND_MOVES			24
#define DG_MOVE_LIST			25
#define DG_KIBITZ			26
#define DG_PEOPLE_IN_MY_CHANNEL		27
#define DG_CHANNEL_TELL			28
#define DG_MATCH			29
#define DG_MATCH_REMOVED		30
#define DG_PERSONAL_TELL		31
#define DG_SHOUT			32
#define DG_MOVE_ALGEBRAIC		33
#define DG_MOVE_SMITH			34
#define DG_MOVE_TIME			35
#define DG_MOVE_CLOCK			36
#define DG_BUGHOUSE_HOLDINGS		37
#define DG_SET_CLOCK			38
#define DG_FLIP				39
#define DG_ISOLATED_BOARD		40
#define DG_REFRESH			41
#define DG_ILLEGAL_MOVE			42
#define DG_MY_RELATION_TO_GAME		43
#define DG_PARTNERSHIP			44
#define DG_SEES_SHOUTS			45
#define DG_CHANNELS_SHARED		46
#define DG_MY_VARIABLE			47
#define DG_MY_STRING_VARIABLE		48
#define DG_JBOARD			49
#define DG_SEEK				50
#define DG_SEEK_REMOVED			51
#define DG_MY_RATING			52
#define DG_SOUND			53
#define DG_PLAYER_ARRIVED_SIMPLE	55
#define DG_MSEC				56
#define DG_BUGHOUSE_PASS		57
#define DG_IP				58
#define DG_CIRCLE			59
#define DG_ARROW			60
#define DG_MORETIME			61
#define DG_PERSONAL_TELL_ECHO		62
#define DG_SUGGESTION			63
#define DG_NOTIFY_ARRIVED		64
#define DG_NOTIFY_LEFT			65
#define DG_NOTIFY_OPEN			66
#define DG_NOTIFY_STATE			67
#define DG_MY_NOTIFY_LIST		68
#define DG_LOGIN_FAILED			69
#define DG_FEN				70
#define DG_TOURNEY_MATCH		71
#define DG_GAMELIST_BEGIN		72
#define DG_GAMELIST_ITEM		73
#define DG_IDLE				74
#define DG_ACK_PING			75
#define DG_RATING_TYPE_KEY              76
#define DG_GAME_MESSAGE                 77
#define DG_UNACCENTED                   78
#define DG_STRINGLIST_BEGIN		79
#define DG_STRINGLIST_ITEM		80
#define DG_DUMMY_RESPONSE               81
#define DG_CHANNEL_QTELL                82
#define DG_PERSONAL_QTELL               83
#define DG_SET_BOARD	                84
#define DG_MATCH_ASSESSMENT             85
#define DG_LOG_PGN                      86
#define DG_NEW_MY_RATING                87
#define DG_LOSERS                       88
#define DG_UNCIRCLE			89
#define DG_UNARROW			90
#define DG_WSUGGEST			91
#define DG_TEMPORARY_PASSWORD           93
#define DG_MESSAGELIST_BEGIN            94
#define DG_MESSAGELIST_ITEM             95
#define DG_LIST				96
#define DG_SJI_AD                       97
#define DG_RETRACT                      99
#define DG_MY_GAME_CHANGE               100
#define DG_POSITION_BEGIN               101
#define DG_DIALOG_START                 105
#define DG_DIALOG_DATA                  106
#define DG_DIALOG_DEFAULT               107
#define DG_DIALOG_END                   108
#define DG_DIALOG_RELEASE               109
#define DG_POSITION_BEGIN2              110
#define DG_PAST_MOVE                    111
#define DG_PGN_TAG                      112
#define DG_IS_VARIATION                 113
#define DG_PASSWORD                     114
#define DG_WILD_KEY                     116


#endif